# Copyright 2021 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

options:
  client-port:
    type: int
    description: |
      Port to listen for client connections.
      See https://zookeeper.apache.org/doc/current/zookeeperStarted.html
    default: 2181
  server-port:
    type: int
    description: |
      Port used by peers to connect to the ZooKeeper leader.
      See https://zookeeper.apache.org/doc/current/zookeeperStarted.html
    default: 2888
  leader-election-port:
    type: int
    description: |
      Additional port used for ZooKeeper leader election.
      See https://zookeeper.apache.org/doc/current/zookeeperStarted.html
    default: 3888
